default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dipak
  password: "vtrans@123"
  host: localhost

development:
  <<: *default
  database: resume_maker_development

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
